export const testBooks = [
    { title: "The Great Gatsby", author: "F. Scott Fitzgerald", category: "Fiction", issueYear: 1925, totalCopies: 5 },
    { title: "To Kill a Mockingbird", author: "Harper Lee", category: "Fiction", issueYear: 1960, totalCopies: 8 },
    { title: "1984", author: "George Orwell", category: "Dystopian", issueYear: 1949, totalCopies: 10 },
    { title: "Brave New World", author: "Aldous Huxley", category: "Dystopian", issueYear: 1932, totalCopies: 7 },
    { title: "The Catcher in the Rye", author: "J.D. Salinger", category: "Fiction", issueYear: 1951, totalCopies: 6 },
    { title: "Sapiens", author: "Yuval Noah Harari", category: "Non-Fiction", issueYear: 2011, totalCopies: 12 },
    { title: "Educated", author: "Tara Westover", category: "Memoir", issueYear: 2018, totalCopies: 4 },
    { title: "The Hobbit", author: "J.R.R. Tolkien", category: "Fantasy", issueYear: 1937, totalCopies: 9 },
    { title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", category: "Fantasy", issueYear: 1997, totalCopies: 15 },
    { title: "The Lord of the Rings", author: "J.R.R. Tolkien", category: "Fantasy", issueYear: 1954, totalCopies: 11 },
    { title: "A Brief History of Time", author: "Stephen Hawking", category: "Science", issueYear: 1988, totalCopies: 6 },
    { title: "The Selfish Gene", author: "Richard Dawkins", category: "Science", issueYear: 1976, totalCopies: 5 },
    { title: "Meditations", author: "Marcus Aurelius", category: "Philosophy", issueYear: 180, totalCopies: 3 },
    { title: "The Republic", author: "Plato", category: "Philosophy", issueYear: -380, totalCopies: 4 },
    { title: "The Alchemist", author: "Paulo Coelho", category: "Fiction", issueYear: 1988, totalCopies: 10 },
    { title: "Thinking, Fast and Slow", author: "Daniel Kahneman", category: "Non-Fiction", issueYear: 2011, totalCopies: 7 },
    { title: "Crime and Punishment", author: "Fyodor Dostoevsky", category: "Fiction", issueYear: 1866, totalCopies: 5 },
    { title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", category: "Fiction", issueYear: 1880, totalCopies: 4 },
    { title: "The Art of War", author: "Sun Tzu", category: "Philosophy", issueYear: -500, totalCopies: 6 },
    { title: "The Road", author: "Cormac McCarthy", category: "Fiction", issueYear: 2006, totalCopies: 8 },
];
